import { useSelector } from "react-redux";
import { RootState } from "@/store/store";
import { AppLanguage } from "@/store/slices/localizationSlice";

type TranslationKey =
  | "common.success"
  | "common.error"
  | "common.cancel"
  | "common.save"
  | "common.language"
  | "settings.title"
  | "settings.selectLanguage"
  | "settings.language.ru"
  | "settings.language.be"
  | "settings.language.en"
  | "storage.download.success"
  | "storage.download.failed"
  | "rooms.download.success"
  | "rooms.download.failed"
  | "rooms.file.downloaded"
  | "storage.file.downloadsShort";

const TRANSLATIONS: Record<AppLanguage, Record<TranslationKey, string>> = {
  ru: {
    "common.success": "Успешно",
    "common.error": "Ошибка",
    "common.cancel": "Отмена",
    "common.save": "Сохранить",
    "common.language": "Язык",
    "settings.title": "Настройки",
    "settings.selectLanguage": "Выберите язык",
    "settings.language.ru": "Русский",
    "settings.language.be": "Беларуская",
    "settings.language.en": "English",
    "storage.download.success": "Файл загружен",
    "storage.download.failed": "Не удалось скачать файл",
    "rooms.download.success": "Успешно",
    "rooms.download.failed": "Не удалось скачать файлы",
    "rooms.file.downloaded": "Файл {{fileId}} загружен",
    "storage.file.downloadsShort": "скач.",
  },
  be: {
    "common.success": "Паспяхова",
    "common.error": "Памылка",
    "common.cancel": "Адмена",
    "common.save": "Захаваць",
    "common.language": "Мова",
    "settings.title": "Налады",
    "settings.selectLanguage": "Абярыце мову",
    "settings.language.ru": "Руская",
    "settings.language.be": "Беларуская",
    "settings.language.en": "English",
    "storage.download.success": "Файл спампаваны",
    "storage.download.failed": "Не ўдалося спампаваць файл",
    "rooms.download.success": "Паспяхова",
    "rooms.download.failed": "Не ўдалося спампаваць файлы",
    "rooms.file.downloaded": "Файл {{fileId}} спампаваны",
    "storage.file.downloadsShort": "загр.",
  },
  en: {
    "common.success": "Success",
    "common.error": "Error",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.language": "Language",
    "settings.title": "Settings",
    "settings.selectLanguage": "Select language",
    "settings.language.ru": "Russian",
    "settings.language.be": "Belarusian",
    "settings.language.en": "English",
    "storage.download.success": "File downloaded",
    "storage.download.failed": "Failed to download file",
    "rooms.download.success": "Success",
    "rooms.download.failed": "Failed to download files",
    "rooms.file.downloaded": "File {{fileId}} downloaded",
    "storage.file.downloadsShort": "downloads",
  },
};

const applyParams = (text: string, params?: Record<string, string | number>) => {
  if (!params) return text;
  return Object.entries(params).reduce(
    (acc, [key, value]) => acc.replaceAll(`{{${key}}}`, String(value)),
    text
  );
};

export const translate = (
  language: AppLanguage,
  key: TranslationKey,
  params?: Record<string, string | number>
) => {
  const dictionary = TRANSLATIONS[language] ?? TRANSLATIONS.ru;
  const template = dictionary[key] ?? TRANSLATIONS.en[key] ?? key;
  return applyParams(template, params);
};

const LITERAL_TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  ru: {
    Back: "Назад",
    Settings: "Настройки",
    "Select Language": "Выберите язык",
    Save: "Сохранить",
    Cancel: "Отмена",
    Success: "Успешно",
    Error: "Ошибка",
    "My Profile": "Мой профиль",
    Home: "Главная",
    Rooms: "Комнаты",
    Storage: "Хранилище",
    Shared: "Общий доступ",
    Chat: "Чат",
    Notifications: "Уведомления",
    Favorites: "Избранное",
    Search: "Поиск",
    "Room Details": "Детали комнаты",
    "Room Not Found": "Комната не найдена",
    "Add New Room": "Создать комнату",
    Create: "Создать",
    "Room Name": "Название комнаты",
    "Enter room name": "Введите название комнаты",
    "Search files": "Поиск файлов",
    "Search connections": "Поиск контактов",
    Skip: "Пропустить",
    Close: "Закрыть",
    "New Files": "Новые файлы",
    "Поддержка": "Поддержка",
    "Обращение": "Обращение",
    "Избранное": "Избранное",
    "Поиск": "Поиск",
    "Поиск файлов и папок...": "Поиск файлов и папок...",
    "Enter file name": "Введите название файла",
    "Enter owner": "Введите владельца",
    "Add Users": "Добавить пользователей",
    "Remove Users": "Удалить пользователей",
    Add: "Добавить",
    Remove: "Удалить",
    "Failed to create room": "Не удалось создать комнату",
    "Room name is required": "Название комнаты обязательно",
    "Create New Room": "Создать комнату",
    "Don't have an account?": "Нет аккаунта?",
    "Sign Up": "Регистрация",
    "Нет доступа к аккаунту?": "Нет доступа к аккаунту?",
    "Поддержка без входа": "Поддержка без входа",
    Preview: "Превью",
    "Хранилище": "Хранилище",
    "свободно": "свободно",
    "из": "из",
    "Connections Search": "Поиск контактов",
    "No notifications yet.": "Пока нет уведомлений.",
    "Updating...": "Обновление...",
    "Sign In": "Войти",
    "Edit Profile": "Редактировать профиль",
    Connections: "Контакты",
    "New Connection": "Новый контакт",
    "No users available": "Пользователи отсутствуют",
    "Upload Preview": "Предпросмотр загрузки",
    Upload: "Загрузить",
    Update: "Обновить",
    "Update File": "Обновить файл",
    "Update Room": "Обновить комнату",
    "Owner:": "Владелец:",
    "File Name:": "Имя файла:",
    "Failed to load avatars": "Не удалось загрузить аватары",
    Loading: "Загрузка",
    "Loading...": "Загрузка...",
    Edit: "Изменить",
    Resources: "Ресурсы",
    "Room Actions": "Действия комнаты",
    "Общие ресурсы": "Общие ресурсы",
    "Нет общих ресурсов": "Нет общих ресурсов",
    "Нет хранилища": "Нет хранилища",
    "Нет избранных элементов": "Нет избранных элементов",
    "Нет данных.": "Нет данных.",
    "Обращение не найдено.": "Обращение не найдено.",
    Friends: "Друзья",
    Requests: "Запросы",
    Files: "Файлы",
    "new File": "новый файл",
    "new Files": "новых файлов",
    "Please wait a moment while we prepare your experience":
      "Подождите немного, мы готовим ваш опыт",
    "Connections (": "Контакты (",
    "Create new": "Создать новое",
    "Search messages…": "Поиск сообщений…",
    "Type a message...": "Введите сообщение...",
    "Preview Mode Toggle (Placeholder)": "Переключатель превью (заглушка)",
    "Create Support Ticket": "Создать обращение",
    "Avatar": "Аватар",
    "Verification Code": "Код подтверждения",
    "Confirm": "Подтвердить",
    "Enter your email": "Введите ваш email",
    "Sign in with Google": "Войти через Google",
    Login: "Войти",
  },
  be: {
    Back: "Назад",
    Settings: "Налады",
    "Select Language": "Абярыце мову",
    Save: "Захаваць",
    Cancel: "Адмена",
    Success: "Паспяхова",
    Error: "Памылка",
    "Успешно": "Паспяхова",
    "Ошибка": "Памылка",
    "Не удалось скачать файл": "Не ўдалося спампаваць файл",
    "Не удалось скачать файлы": "Не ўдалося спампаваць файлы",
    "Элемент восстановлен": "Элемент адноўлены",
    "Не удалось восстановить элемент": "Не ўдалося аднавіць элемент",
    "Удалить навсегда?": "Выдаліць назаўсёды?",
    "Это действие нельзя отменить": "Гэта дзеянне нельга адмяніць",
    "Удалить": "Выдаліць",
    "Элемент удален навсегда": "Элемент выдалены назаўсёды",
    "Не удалось удалить элемент": "Не ўдалося выдаліць элемент",
    "Корзина": "Кошык",
    "Нельзя восстановить": "Нельга аднавіць",
    "Сначала восстановите родительскую папку из корзины.": "Спачатку адновіце бацькоўскую папку з кошыка.",
    "Очистить корзину?": "Ачысціць кошык?",
    "Удалить всё": "Выдаліць усё",
    "Удаление": "Выдаленне",
    "Запрос не выполнен": "Запыт не выкананы",
    "Для выбранных папок сначала восстановите родителя в корзине.": "Для выбраных папак спачатку адновіце бацькоўскую ў кошыку.",
    "Восстановление": "Аднаўленне",
    "Восстановить доступные?": "Аднавіць даступныя?",
    "Восстановить": "Аднавіць",
    "Удалить навсегда": "Выдаліць назаўсёды",
    "Очистить всё": "Ачысціць усё",
    "Корзина пуста": "Кошык пусты",
    "My Profile": "Мой профіль",
    Home: "Галоўная",
    Rooms: "Пакоі",
    Storage: "Сховішча",
    Shared: "Агульны доступ",
    Chat: "Чат",
    Notifications: "Апавяшчэнні",
    Favorites: "Выбранае",
    Search: "Пошук",
    "Room Details": "Дэталі пакоя",
    "Room Not Found": "Пакой не знойдзены",
    "Add New Room": "Стварыць пакой",
    "Create New Room": "Стварыць пакой",
    Create: "Стварыць",
    "Room Name": "Назва пакоя",
    "Enter room name": "Увядзіце назву пакоя",
    "Search files": "Пошук файлаў",
    "Search connections": "Пошук кантактаў",
    Skip: "Прапусціць",
    Close: "Закрыць",
    "New Files": "Новыя файлы",
    "Поддержка": "Падтрымка",
    "Обращение": "Зварот",
    "Избранное": "Выбранае",
    "Поиск": "Пошук",
    "Поиск файлов и папок...": "Пошук файлаў і папак...",
    "Чтение": "Чытанне",
    "Запись": "Запіс",
    "Администратор": "Адміністратар",
    "Недостаточно места": "Недастаткова месца",
    "Введите название": "Увядзіце назву",
    "Введите название тега": "Увядзіце назву тэга",
    "Теги": "Тэгі",
    "Конвертация": "Канвертацыя",
    "Архивировать": "Архіваваць",
    "Тема": "Тэма",
    "Кратко, в чём суть": "Каротка, у чым сутнасць",
    "Описание": "Апісанне",
    "Подробности": "Падрабязнасці",
    "Email для связи": "Email для сувязі",
    "Опишите проблему. После отправки доступ к тикету сохранится на устройстве.": "Апішыце праблему. Пасля адпраўкі доступ да звароту застанецца на прыладзе.",
    "Мы ответим на обращение в разделе «Мои обращения».": "Мы адкажам у раздзеле «Маё звароты».",
    "Информация о папке": "Інфармацыя пра папку",
    "Информация о файле": "Інфармацыя пра файл",
    "Не указано": "Не пазначана",
    "Готово": "Гатова",
    "Файл сконвертирован и сохранён": "Файл сканвертаваны і захаваны",
    "Не удалось конвертировать": "Не ўдалося канвертаваць",
    "Создано файлов:": "Створана файлаў:",
    "Новое обращение": "Новы зварот",
    "Новое обращение (сбросить доступ)": "Новы зварот (скінуць доступ)",
    "Сбросить доступ?": "Скінуць доступ?",
    "Без сохранённого токена вы не сможете открыть это обращение с этого устройства.": "Без захаванага токена вы не зможаце адкрыць гэты зварот з гэтай прылады.",
    "Сбросить": "Скінуць",
    "Enter file name": "Увядзіце назву файла",
    "Enter owner": "Увядзіце ўладальніка",
    "Add Users": "Дадаць карыстальнікаў",
    "Remove Users": "Выдаліць карыстальнікаў",
    Add: "Дадаць",
    Remove: "Выдаліць",
    "Failed to create room": "Не ўдалося стварыць пакой",
    "Room name is required": "Назва пакоя абавязковая",
    "Don't have an account?": "Няма акаўнта?",
    "Sign Up": "Рэгістрацыя",
    "Нет доступа к аккаунту?": "Няма доступу да акаўнта?",
    "Поддержка без входа": "Падтрымка без уваходу",
    Preview: "Перадпрагляд",
    "Хранилище": "Сховішча",
    "свободно": "вольна",
    "из": "з",
    "Connections Search": "Пошук кантактаў",
    "No notifications yet.": "Пакуль няма апавяшчэнняў.",
    "Updating...": "Абнаўленне...",
    "Sign In": "Увайсці",
    "Edit Profile": "Рэдагаваць профіль",
    Connections: "Кантакты",
    "New Connection": "Новы кантакт",
    "No users available": "Карыстальнікі адсутнічаюць",
    "Upload Preview": "Перадпрагляд загрузкі",
    Upload: "Загрузіць",
    Update: "Абнавіць",
    "Update File": "Абнавіць файл",
    "Update Room": "Абнавіць пакой",
    "Owner:": "Уладальнік:",
    "File Name:": "Назва файла:",
    "Failed to load avatars": "Не ўдалося загрузіць аватары",
    Loading: "Загрузка",
    "Loading...": "Загрузка...",
    Edit: "Змяніць",
    Resources: "Рэсурсы",
    "Room Actions": "Дзеянні пакоя",
    "Общие ресурсы": "Агульныя рэсурсы",
    "Нет общих ресурсов": "Няма агульных рэсурсаў",
    "Нет хранилища": "Няма сховішча",
    "Нет избранных элементов": "Няма выбраных элементаў",
    "Нет данных.": "Няма дадзеных.",
    "Обращение не найдено.": "Зварот не знойдзены.",
    Friends: "Сябры",
    Requests: "Запыты",
    Files: "Файлы",
    "new File": "новы файл",
    "new Files": "новых файлаў",
    "Please wait a moment while we prepare your experience":
      "Пачакайце крыху, мы падрыхтоўваем ваш досвед",
    "Connections (": "Кантакты (",
    "Create new": "Стварыць новае",
    "Search messages…": "Пошук паведамленняў…",
    "Type a message...": "Увядзіце паведамленне...",
    "Preview Mode Toggle (Placeholder)": "Пераключальнік прагляду (заглушка)",
    "Create Support Ticket": "Стварыць зварот",
    "Avatar": "Аватар",
    "Verification Code": "Код пацвярджэння",
    "Confirm": "Пацвердзіць",
    "Enter your email": "Увядзіце ваш email",
    "Sign in with Google": "Увайсці праз Google",
    Login: "Увайсці",
  },
  en: {
    Back: "Back",
    Settings: "Settings",
    "Select Language": "Select language",
    Save: "Save",
    Cancel: "Cancel",
    Success: "Success",
    Error: "Error",
    "Успешно": "Success",
    "Ошибка": "Error",
    "Не удалось скачать файл": "Failed to download file",
    "Не удалось скачать файлы": "Failed to download files",
    "Элемент восстановлен": "Item restored",
    "Не удалось восстановить элемент": "Failed to restore item",
    "Удалить навсегда?": "Delete permanently?",
    "Это действие нельзя отменить": "This action cannot be undone",
    "Удалить": "Delete",
    "Элемент удален навсегда": "Item deleted permanently",
    "Не удалось удалить элемент": "Failed to delete item",
    "Корзина": "Trash",
    "Нельзя восстановить": "Cannot restore",
    "Сначала восстановите родительскую папку из корзины.": "Restore parent folder from trash first.",
    "Очистить корзину?": "Clear trash?",
    "Удалить всё": "Delete all",
    "Удаление": "Deletion",
    "Запрос не выполнен": "Request failed",
    "Для выбранных папок сначала восстановите родителя в корзине.": "Restore parent for selected folders first.",
    "Восстановление": "Restore",
    "Восстановить доступные?": "Restore available items?",
    "Восстановить": "Restore",
    "Удалить навсегда": "Delete permanently",
    "Очистить всё": "Clear all",
    "Корзина пуста": "Trash is empty",
    "My Profile": "My Profile",
    Home: "Home",
    Rooms: "Rooms",
    Storage: "Storage",
    Shared: "Shared",
    Chat: "Chat",
    Notifications: "Notifications",
    Favorites: "Favorites",
    Search: "Search",
    "Room Details": "Room Details",
    "Room Not Found": "Room Not Found",
    "Add New Room": "Add New Room",
    "Create New Room": "Create New Room",
    Create: "Create",
    "Room Name": "Room Name",
    "Enter room name": "Enter room name",
    "Search files": "Search files",
    "Search connections": "Search connections",
    Skip: "Skip",
    Close: "Close",
    "New Files": "New Files",
    "Поддержка": "Support",
    "Обращение": "Ticket",
    "Избранное": "Favorites",
    "Поиск": "Search",
    "Поиск файлов и папок...": "Search files and folders...",
    "Чтение": "Read",
    "Запись": "Write",
    "Администратор": "Administrator",
    "Недостаточно места": "Not enough space",
    "Введите название": "Enter name",
    "Введите название тега": "Enter tag name",
    "Теги": "Tags",
    "Конвертация": "Conversion",
    "Архивировать": "Archive",
    "Тема": "Subject",
    "Кратко, в чём суть": "Brief summary",
    "Описание": "Description",
    "Подробности": "Details",
    "Email для связи": "Contact email",
    "Опишите проблему. После отправки доступ к тикету сохранится на устройстве.": "Describe the issue. After submit, ticket access will stay on this device.",
    "Мы ответим на обращение в разделе «Мои обращения».": "We will reply in the My tickets section.",
    "Информация о папке": "Folder info",
    "Информация о файле": "File info",
    "Не указано": "Not specified",
    "Готово": "Done",
    "Файл сконвертирован и сохранён": "File converted and saved",
    "Не удалось конвертировать": "Failed to convert",
    "Создано файлов:": "Files created:",
    "Новое обращение": "New ticket",
    "Новое обращение (сбросить доступ)": "New ticket (reset access)",
    "Сбросить доступ?": "Reset access?",
    "Без сохранённого токена вы не сможете открыть это обращение с этого устройства.": "Without a saved token, you cannot open this ticket on this device.",
    "Сбросить": "Reset",
    "Enter owner": "Enter owner",
    "Нет доступа к аккаунту?": "No account access?",
    "Поддержка без входа": "Support without login",
    Preview: "Preview",
    "Хранилище": "Storage",
    "свободно": "free",
    "из": "of",
    "Connections Search": "Connections Search",
    "No notifications yet.": "No notifications yet.",
    "Updating...": "Updating...",
    "Sign In": "Sign In",
    "Edit Profile": "Edit Profile",
    Connections: "Connections",
    "New Connection": "New Connection",
    "No users available": "No users available",
    "Upload Preview": "Upload Preview",
    Upload: "Upload",
    Update: "Update",
    "Update File": "Update File",
    "Update Room": "Update Room",
    "Owner:": "Owner:",
    "File Name:": "File Name:",
    "Failed to load avatars": "Failed to load avatars",
    Loading: "Loading",
    "Loading...": "Loading...",
    Edit: "Edit",
    Resources: "Resources",
    "Room Actions": "Room Actions",
    "Общие ресурсы": "Shared resources",
    "Нет общих ресурсов": "No shared resources",
    "Нет хранилища": "No storage",
    "Нет избранных элементов": "No favorite items",
    "Нет данных.": "No data.",
    "Обращение не найдено.": "Ticket not found.",
    Friends: "Friends",
    Requests: "Requests",
    Files: "Files",
    "new File": "new File",
    "new Files": "new Files",
    "Please wait a moment while we prepare your experience":
      "Please wait a moment while we prepare your experience",
    "Connections (": "Connections (",
    "Create new": "Create new",
    "Search messages…": "Search messages…",
    "Type a message...": "Type a message...",
    "Preview Mode Toggle (Placeholder)": "Preview Mode Toggle (Placeholder)",
    "Create Support Ticket": "Create Support Ticket",
    "Avatar": "Avatar",
    "Verification Code": "Verification Code",
    "Confirm": "Confirm",
    "Enter your email": "Enter your email",
    "Sign in with Google": "Sign in with Google",
    Login: "Login",
  },
};

export const translateLiteral = (language: AppLanguage, text: string) => {
  const normalized = text.trim();
  if (!normalized) return text;
  return LITERAL_TRANSLATIONS[language]?.[normalized] ?? text;
};

export const useI18n = () => {
  const language = useSelector((state: RootState) => state.localization.language);
  return {
    language,
    t: (key: TranslationKey, params?: Record<string, string | number>) =>
      translate(language, key, params),
    tl: (text: string) => translateLiteral(language, text),
  };
};
